# Generated by Django 5.0.2 on 2024-08-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_Organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='x_starting_place',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='y_starting_place',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tourpoint',
            name='axis_x',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tourpoint',
            name='axis_y',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
